class_name GameConfig

const VIEWPORT_HEIGHT := 256.0
const GROUND_HEIGHT := 32.0
const GROUND_TOP_Y := VIEWPORT_HEIGHT - GROUND_HEIGHT
const BIRD_SCREEN_FRACTION_X := 0.28

const SCROLL_SPEED := 60.0
const BACKGROUND_PARALLAX_FACTOR := 0.2

const GRAVITY := 600.0
const FLAP_VELOCITY := -190.0
const MAX_FALL_SPEED := 300.0

const PIPE_GAP := 58.0
const PIPE_SPAWN_INTERVAL := 1.5
const PIPE_VERTICAL_MARGIN := 24.0
